version: "2.1"
services:
  web:
    build: .
    command:  bash -c "flask db init || flask db migrate || flask db upgrade && python3 app.py"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pycastdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10